version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/express-app
hooks:
  ApplicationStop:
    - location: src/index.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: src/index.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: src/index.sh
      timeout: 60
      runas: root