version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/express-app
hooks:
  ApplicationStop:
    - location: src/index.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: src/index.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: src/index.sh
      timeout: 300
      runas: ec2-user